sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: vUfPZjML+LuhU6FC+1ykElVYlkYJ3iHva0qDmuMGo/GUAgrfJ2mhJfDGSfE9yuHphefExhZktkUparLzl8aO/NMWg6iF3i5FWLIbvm/D4d5pDMkmghGmkpIZp0MTfEX0jYCUIernqBIEBTDQylghJPHzdjMMTjDfHNYxziBUb/QrIBfPyJnuiJEIDLbJWpzBSyiZrf5LGPmzfkM3hHyxI8KTEtyJw6LvIikh+8mlHPa4AEJszl/hO4ZNNCcyciD8h1vCjSs2Ku/sHEVhtd66NvvajFney8iKD8r/DQ45ljGWTn+mWJ2gzKU8otrtXHD/9Z/kdNN0l8lw5SsBmu6w8IMOEtqPtBni/RpTi6gNZnjiwHjAiFlUbtpwXKIXrqJyw26xr1bnRtThX2LHpMahHRzJls5ofWCWrG5+FHRFTsBokiUcuoa/MrmGzJM9+ghBrbynJwFkSc48agdplZrYIj67RYRYz81JcoDhIShn8A7Ts5sWSNFV0NEx5rPbIuLxUUCjrqhS868L4jxLlZ4z7gqEABZM7zA3uTCFEocSPU6KoIIj3k0YEFp9qukqepzhaN4AS1jVSQkmeBAbHh8sqoxPIJ4XvByRxu8cmCyV9Bt851VKS5juQptglNZZ60XY+2R/pmJHJq0Kyx5HbE1TZJlf0A9Ubj4AqENRwcH3elk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Prince-and-the-Pauper_1837
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy